### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by noraj** [goatandsheep/issuehunt-action#1]
How to integrate it in a new github workflow?

I tried:

```yml

name: Create IssueHunt comment for opened issues
on:
  issues:
    types: [opened, reopened]
jobs:
  comment:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
     - name: Create IssueHunt comment for opened issues
       uses: goatandsheep/issuehunt-action@v1.0.0
```

But it doesn't work.

It seems broken: https://github.com/noraj/haiti/actions/runs/4162616484
